#!/bin/bash
echo "📱 PRZYGOTOWANIE DO UPLOADU Z TELEFONU"
echo "======================================"
echo ""
echo "📦 Twój plik gotowy do wysłania:"
echo "   ICE_METROPOLIS_FINAL.zip"
echo ""
echo "🌐 KROKI:"
echo "1. Otwórz przeglądarkę"
echo "2. Wejdź na: app.netlify.com/drop"
echo "3. Kliknij 'Select folder'"
echo "4. Wybierz ICE_METROPOLIS_FINAL.zip"
echo "5. Poczekaj na URL"
echo ""
echo "📍 Lokalizacja pliku:"
echo "$(pwd)/ICE_METROPOLIS_FINAL.zip"
